version: '3'
services:
  mlflow:
    image: mlflow/mlflow
    ports:
      - 5000:5000
    volumes:
      - ./mlflow:/mlflow
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:////mlflow/mlflow.db
    command: server --host 0.0.0.0 --default-artifact-root /mlflow/artifacts --backend-store-uri sqlite:////mlflow/mlflow.db

  airflow-scheduler:
    image: apache/airflow
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False

  airflow-webserver:
    image: apache/airflow
    ports:
      - 8080:8080
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    command: webserver

